version: '3'
services:
  go:
    image: golang:1.13-alpine
    command: ['/bin/sh', '-c', 'while true; do :; sleep 1; done']
    depends_on:
      - redis
      - db
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_PORT: 5432
      DB_HOST: db
    expose:
      - 8082
    ports:
      - '8082:8082'
    volumes:
      - './go/:/go'
    working_dir: '/go'
