version: '3'
services:
  go:
    image: golang:1.13-alpine
    command: ['/bin/sh', '-c', 'while true; do :; sleep 1; done']
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - './go/:/go'
    working_dir: '/go'
