version: '3'
services:
  redis:
    image: redis:5.0.7-alpine
    expose:
      - 6379
    ports:
      - '6379:6379'
  db:
    image: postgres:12-alpine
    expose:
      - 5432
    ports:
      - '5432:5432'
    volumes:
      - '/var/lib/pgsql/data'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'trendysnaps'
  graphql-engine:
    image: hasura/graphql-engine:v1.1.0
    ports:
      - '8080:8080'
    depends_on:
      - 'db'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@db:5432/trendysnaps
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
